name: Deploy to Firebase  

on:
  push:
    branches:
      - production  # Triggers on push to the production branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Create .env file
        run: |
          echo "VITE_API_KEY=${{ vars.VITE_API_KEY }}" >> .env
          echo "VITE_AUTH_DOMAIN=${{ vars.VITE_AUTH_DOMAIN }}" >> .env
          echo "VITE_PROJECT_ID=${{ vars.VITE_PROJECT_ID }}" >> .env
          echo "VITE_STORAGE_BUCKET=${{ vars.VITE_STORAGE_BUCKET }}" >> .env
          echo "VITE_MESSAGING_SENDER_ID=${{ vars.VITE_MESSAGING_SENDER_ID }}" >> .env
          echo "VITE_APP_ID=${{ vars.VITE_APP_ID }}" >> .env
          echo "VITE_MEASUREMENT_ID=${{ vars.VITE_MEASUREMENT_ID }}" >> .env

      - name: Install Dependencies
        run: npm install

      - name: Install Terser (Required for Minification)
        run: npm install terser -D

      - name: Build Project
        run: npm run build

      - name: Deploy to Firebase
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: firebase deploy --only hosting --project ${{ vars.VITE_PROJECT_ID }}
