name: Deploy to Firebase  

on:
  push:
    branches:
      - production  

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Create .env file
        run: |
          touch .env
          printf "VITE_API_KEY=%s\n" "${{ vars.VITE_API_KEY }}" >> .env
          printf "VITE_AUTH_DOMAIN=%s\n" "${{ vars.VITE_AUTH_DOMAIN }}" >> .env
          printf "VITE_PROJECT_ID=%s\n" "${{ vars.VITE_PROJECT_ID }}" >> .env
          printf "VITE_STORAGE_BUCKET=%s\n" "${{ vars.VITE_STORAGE_BUCKET }}" >> .env
          printf "VITE_MESSAGING_SENDER_ID=%s\n" "${{ vars.VITE_MESSAGING_SENDER_ID }}" >> .env
          printf "VITE_APP_ID=%s\n" "${{ vars.VITE_APP_ID }}" >> .env
          printf "VITE_MEASUREMENT_ID=%s\n" "${{ vars.VITE_MEASUREMENT_ID }}" >> .env

      - name: Install Dependencies
        run: npm install

      - name: Install Terser (Required for Minification)
        run: npm install terser -D

      - name: Build Project
        run: npm run build

      - name: Authenticate Firebase
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > $HOME/firebase-key.json
          chmod 600 $HOME/firebase-key.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/firebase-key.json" >> $GITHUB_ENV

      - name: Deploy to Firebase
        run: |
          set -e
          firebase deploy --only hosting --project ${{ vars.VITE_PROJECT_ID }}
